site_name: pqlattice - docs
repo_url: https://github.com/mikolajlh/pqlattice/
site_description: "Documentation for Python library for lattice based cryptography and cryptoanalysis"
site_author: "Miko≈Çaj Leonhardt"
theme:
  name: material
